alias dotfiles='/usr/bin/git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME"'
alias cl='clear'
alias vi='nvim'
alias vim='nvim'
alias gst='git status'
alias gp='git push'
alias gl='git pull'
alias gc='git commit'
alias gco='git checkout'
alias gcl='git clone'
alias gd='git diff'
alias gds='git diff --staged'
alias glog='git log --graph'
